version: "3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql
    environment:
      TZ: Asia/Seoul
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
    env_file:
      - .env.db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --range_optimizer_max_mem_size=16777216
    restart: always
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
